### ISSUE TITLE
观影控制不能成功控制（b站测的），难道使用前需要自己添加动作？

### ISSUE THREAD

**Issue by jsonhet** [Mr-xiaobing/CMSGS#1]

**Comment by Mr-xiaobing** [comment]
并不需要自己添加动作，所有的动作都没有效果么，还是一些动作不行。
代码有报错么。如果有报错的话，可以提供一下打印的错误信息。
观影模式的判断类放在了service里面ControlVideoPlay里面。也有可能是做的动作不够标准，达不到判断条件的要求。
现在的readme很水，我会出一个新的readme的。

**Comment by jsonhet** [comment]
所有动作都无效，没有报错 点了观影模式action窗口里有视频，有识别节点，但是浏览器没反应。win11 Chrome edge都试了

**Comment by Mr-xiaobing** [comment]
可以看看能不能在文本上打出字母来，如果可以的话，有可能是快捷键冲突了。
实在不行的话，我可能也没办法了。我并没有复现出这个bug。
